# Generated by Django 4.2 on 2025-08-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_auto_20250801_0145"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="link",
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="payment",
            name="session_id",
            field=models.CharField(max_length=500),
        ),
    ]
